ENABLED_GROUPS = "ENABLED_GROUPS"

# group
SUFFIX_ENABLED_CHANNELS = "ENABLED_CHANNELS"
SUFFIX_TOKEN = "TOKEN"

# channel
SUFFIX_TYPE = "TYPE"
# bark
SUFFIX_BARK_URL = "BARK_URL"
SUFFIX_BARK_KEY = "BARK_KEY"
# Wecom webhook key，see https://developer.work.weixin.qq.com/document/path/91770
SUFFIX_WECOM_KEY = "WECOM_WEBHOOK_KEY"
# Wecom corpid and secret，see https://developer.work.weixin.qq.com/document/path/91039
SUFFIX_WECOM_CORP_ID = "WECOM_CORP_ID"
SUFFIX_WECOM_AGENT_ID = "WECOM_AGENT_ID"
SUFFIX_WECOM_SECRET = "WECOM_SECRET"
# Pushover, see https://pushover.net/api
SUFFIX_PUSHOVER_TOKEN = "PUSHOVER_TOKEN"
SUFFIX_PUSHOVER_USER = "PUSHOVER_USER"
# PushDeer, see http://pushdeer.com/
SUFFIX_PUSHDEER_TOKEN = "PUSHDEER_TOKEN"
# Chanify, see https://github.com/chanify/chanify
SUFFIX_CHANIFY_ENDPOINT = "CHANIFY_ENDPOINT"
SUFFIX_CHANIFY_TOKEN = "CHANIFY_TOKEN"
# SMTP mail
SUFFIX_EMAIL_HOST = "EMAIL_HOST"
SUFFIX_EMAIL_PORT = "EMAIL_PORT"
SUFFIX_EMAIL_USER = "EMAIL_USER"
SUFFIX_EMAIL_PASSWORD = "EMAIL_PASSWORD"
SUFFIX_EMAIL_SENDER = "EMAIL_SENDER"
SUFFIX_EMAIL_TO = "EMAIL_TO"
SUFFIX_EMAIL_STARTTLS = "EMAIL_STARTTLS"
# Discord
SUFFIX_DISCORD_WEBHOOK_ID = "DISCORD_WEBHOOK_ID"
SUFFIX_DISCORD_WEBHOOK_TOKEN = "DISCORD_WEBHOOK_TOKEN"
# Telegram
SUFFIX_TELEGRAM_TOKEN = "TELEGRAM_TOKEN"
SUFFIX_TELEGRAM_CHAT_ID = "TELEGRAM_CHAT_ID"
